# Stage 1: Компиляция
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /app
COPY src ./src
RUN javac -d . src/main/java/ru/mentee/power/SimpleWebServer.java

# Stage 2: Запуск
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/ru/mentee/power/SimpleWebServer.class ./ru/mentee/power/
EXPOSE 8080
CMD ["java", "-Dfile.encoding=UTF-8", "ru.mentee.power.SimpleWebServer"]