# Stage 1: Компиляция
FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /app
COPY src ./src
RUN javac -d . src/main/java/ru/mentee/power/TextAnalyzer.java

# Stage 2: Запуск
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/ru/mentee/power/TextAnalyzer.class ./ru/mentee/power/
ENTRYPOINT ["java", "ru.mentee.power.TextAnalyzer"]