version: '3.8'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile.calculator
    image: calculator:v1.0
    container_name: mcloud-calculator
    stdin_open: true
    tty: true

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    image: webserver:v1.0
    container_name: mcloud-webserver
    ports:
      - "8080:8080"
  game:
    build:
      context: .
      dockerfile: Dockerfile.game
    image: game:v1.0
    stdin_open: true
    tty: true

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    image: analyzer:v1.0

  spring-optimization:
    build:
      context: .
      dockerfile: src/main/java/ru/mentee/power/spring/Dockerfile.original
    image: spring-boot:fat
    container_name: mcloud-spring-fat
    ports:
      - "8081:8081"

  spring-optimized:
    build:
      context: .
      dockerfile: src/main/java/ru/mentee/power/spring/Dockerfile.optimized
    image: spring-boot:slim
    container_name: mcloud-spring-slim
    ports:
      - "8082:8082"